### ISSUE TITLE
Make Search icon clickable when main menu is open, closing main menu

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#118] opened 2021-10-26 20:01 UTC
On mobile, when Library submenu is open (displaying Favorites Collection Playlists History X), the Search icon is becomes unclickable. The user needs to click the X and close their menu before being able to use Search, but it is unlikely the user will know this is the reason Search is "not working".

On mobile, whenever the user clicks the Search icon, it should automatically close their main menu and open the search bar.

**Comment by gitaaron** [comment] 2021-11-03 05:55
Please sign me up for this.

**Comment by gitaaron** [comment] 2021-11-03 16:47
@hakanto  I found a few other issues while looking closer at the UX here.

1.  If I search for something in wide screen mode (eg/ 'ambient') then click browse I still see the search bar with text 'ambient' leading me to believe I am still searching on 'ambient'.

2.  If I search for something in small screen mode then click 'browse' or 'library' it still shows me the search results in the main content panel.

I'd recommend limiting the scope of this issue to simply making it possible to click the search icon and not navigating back.  

I'd also recommend opening a separate issue to ensure the routing logic is working properly in the following scenarios in both wide and small screens.

1.  Searching for something.

2. Clicking 'browse',  'discover' and 'library'.

(I can get to that next if it makes sense)

Finally, I'd recommend raising the following discussion points -

1.  Making the display of the expanded search dialog with other top level menu items mutually exclusive (ie/ make it possible to either 'search' or 'view my library').  This would address the first issue and seems to be consistent with how other music apps do this.  Another option could be to always clear the search when I click one of the other top level menu items but that might lead to other issues.

2.  IMHO browse and discover sound very similar.  Perhaps it would make sense to remove 'discover' from the top level menu as an option since 'home' is already 'discover'.

3.  It seems like there is overlap between 'browse' and 'search' and I foresee myself wanting to search for other parts under 'browse'.  Perhaps the sitemap could be rethought a little so they are combined into one.

4.  Possibly impacts the previous discussion point - a nice to have for power users might be to make their library searchable.

**Comment by peterklingelhofer** [comment] 2022-01-12 02:06
Thank you for @gitaaron for raising these valuable insights. I'm going to address the rest in time so I don't bite off more than I can chew, this issue you raised is sort of independent of the others so I'm going to address that first:

> 2. IMHO browse and discover sound very similar. Perhaps it would make sense to remove 'discover' from the top level menu as an option since 'home' is already 'discover'.

With respect to this point raised by @gitaaron above - I completely agree, on a typical website clicking the website's home button/logo (in our case, in the top left, as it is with most websites) directs the user to the homepage, which it does. Having another `Discover` button is redundant. Many folks are probably already fairly familiar with and expect this UI pattern on other mainstream streaming platforms - the homepage is a place for music discovery.

Given that, it might be advisable to remove the `Discover` button entirely, and make the actual homepage URL https://stream.resonate.coop or https://stream.resonate.coop/home instead of https://stream.resonate.coop/discover. Having your homepage redirect to a `pathname` other than `/home` is also fairly atypical for the majority of modern websites for example, so this would address that slightly unusual behavior as well.

I don’t have strong feelings either way, but my initial inclination is that https://stream.resonate.coop is really simple, minimal, professional, clean and easy to read/comprehend, and it draws more emphasis to the `.coop` and helps to underscore the cooperative nature of this project, which seem to be pluses.

**Comment by peterklingelhofer** [comment] 2022-01-20 13:38
@fgblomqvist, I've been digging into this one a bit. Do you have any ideas? The issue seems to stem from `.emit('search:toggle')` and `.emit('library:toggle')` (just search the codebase for those, there aren't too many usages) behaving slightly mutually exclusively where they shouldn't be. The strange thing though is that if the user clicks any of the options while Library is open (e.g Playlists) and then clicks the Search, it seems to work as intended, so it's only if we open the Library pane at the bottom and don't select an item. I also saw an error in the console related to some sort of hack that `choojs` has setup for IE/Edge. Unfortunately, it appears that [choojs](https://github.com/choojs/choo) hasn't been updated since April of 2019, which is slightly concerning...

Thankfully, we have some work being done on a mobile Android/iOS [app](https://community.resonate.is/t/ios-android-app-volunteer/2284/15), but that's only just begun.

**Comment by fgblomqvist** [comment] 2022-01-20 16:38
I'll take a look at a little later today, sounds like an interesting bug 🤔  

It indeed looks pretty grim regarding choojs. Sounds like they sorta lost traction (https://github.com/choojs/choo/issues/686). I've never heard of it before this project so perhaps not too surprised. Probably worth having a discussion regarding it in the near-term.

**Comment by fgblomqvist** [comment] 2022-01-20 20:35
I see an error in console when clicking the close button (the X in the search header, getting `this.element is undefined`), but that is most likely unrelated.

I did some debugging regarding the `search:toggle` event and everything fires as expected. The render logic is quite complex imo, and I've never worked with choojs before, but what I see is this:
1. It tries to replace the element in the header with the class `.search` with the new version (which will either be the displayed search or the hidden search depending on the state).
2. Normally this works fine, however, when one of the submenus at the bottom of the page opens, such as the "Browse" or "Library" menu, the `.search` element disappears (as in, gets removed from the DOM). As in, when you open one of the submenus, the `.search` disappears, when you close it, the `.search` appears again.
3. Since there is no `.search` element present, it can't be replaced with the displayed search. This why things don't work.

Now, why is the `.search` element getting removed when I open one of the submenus at the bottom of the page? Not sure yet. I can keep digging later this week unless someone figures it out before me. Have to get a better grip around how things work.

**Comment by fgblomqvist** [comment] 2022-01-21 00:41
Hah I figured it out!
The problem is here:
https://github.com/resonatecoop/stream/blob/development/beta/components/header/index.js#L279-L290

When a submenu is rendered the search isn't rendered. Only when no submenu is rendered is the search rendered. Easy to fix.

I will submit a PR tomorrow. There are some styles in this code that makes it a lot harder to read than it has to be (the way dictionaries are used to form some sort of ternary expressions for example). I'll include some suggestions regarding that in the PR as well :slightly_smiling_face:

**Closed as completed** 2022-01-24 15:49 UTC
Labels: bug, enhancement, help wanted
