### ISSUE TITLE
Tracks unable to play due to “corruption or unsupported features on browser”

### ISSUE THREAD

**Issue by hakanto** [resonatecoop/stream2own#83] opened 2021-06-01 21:06 UTC
Some tracks that were uploaded in the early days of Resonate are having playback issues on particular browsers, prompting this error message:

_“The audio playback was aborted due to a corruption problem or because the video used features your browser did not support.”_

I’ve encountered the issue on Android Chrome PWA for Players 6 and 7. It doesn’t occur on Firefox Mobile.

The following songs have prompted the error:

* 795 - Earnest and without you - Dreams Pt.II
* 800 - Klinke auf Cinch - Time
* 58 - Stephanie Merchak - Circular Thoughts
* 823 - Stephanie Merchak- Back To Sleep

**Comment by hakanto** [comment] 2021-10-26 20:04
Tried again on Android Chrome PWA for Player 7. Unable to play tracks.

**Comment by peterklingelhofer** [comment] 2022-04-24 02:19
I can confirm I also get the error for the above songs on iOS as well.

A user [reported](https://community.resonate.is/t/testing-minimal-apps-for-android-and-ios/2613/108) and I [confirmed](https://community.resonate.is/t/testing-minimal-apps-for-android-and-ios/2613/111?u=peterklingelhofer) a _similar_ but not identical issue:

> The first six tracks on that album [The Trip](https://stream.resonate.coop/artist/1295/release/the-trip) by [Sommon Cense](https://stream.resonate.coop/artist/1295) both don’t load for me either in the mobile app or web browser as of right now (both on my actual phone and in the simulator), but the rest of the album does. I'm not set up to run the server locally yet so I can't see more details about the server error that is happening though. I'm curious if Android users can load it on their phones. I wonder if these to two tracks are in a different (and unsupported on mobile) filetype? This is the first time I've seen this error myself. The tracks play fine in the [web player](https://stream.resonate.coop/discover) so it's weird the server would handle a request from the app differently (it uses your phone's default browser to make the request), and again, the same issue is also present when I try to play that album in my phone's browser.

**Comment by simonv3** [comment] 2022-04-24 11:11
In Firefox: it looks like while this works fine in the `audio` tag inside HTML, when I reference that streamed file directly in the browser it does complain that the file is corrupt: 

https://api.resonate.coop/v1/stream/418

**Comment by peterklingelhofer** [comment] 2022-08-16 02:50
This is fixed now: https://stream.resonate.coop/artist/1295/release/the-trip.

**Closed as completed by peterklingelhofer** 2022-08-16 02:50 UTC
Labels: bug, 7.x, 6, mobile
