### ISSUE TITLE
After logging in to player the login button does not change to a profile

### ISSUE THREAD

**Issue by jackhajb** [resonatecoop/stream2own#158] opened 2022-01-28 18:12 UTC
### Description
Unable to access the user dropdown after logging in to the player on the dev environment.

### Steps to reproduce

1.  Navigate to `https://id.resonate.ninja/`
2.  Click `Player`
3.  Input login information
4. You will be brought to the continue to login page
5.  Click `Finish login`
6. You will be brought to the streaming player
7. The button in the header on the top right will still say login

### Expected Results vs Actual Results
Expected: The profile button to be visible in the top right of the header and to have access to the user dropdown

Actual: The login button is visible in the top right of the header and clicking it brings you to the Continue to login page described in `step 4` of the steps to reproduce

### Source URL
`https://id.resonate.ninja/`

### Environment
Chrome Version 97.0.4692.99 (Official Build) (x86_64)

**Comment by jackhajb** [comment] 2022-01-28 18:13
https://user-images.githubusercontent.com/47801503/151599684-1863c4c4-3dc0-440f-bdbb-cde5dcb88c66.mov

**Comment by auggod** [comment] 2022-01-30 01:35
I was not able reproduce this on brave or chrome. Can you confirm it still happen?

**Comment by peterklingelhofer** [comment] 2022-02-02 02:55
> I was not able reproduce this on brave or chrome. Can you confirm it still happen?

@auggod, I created an account on `https://id.resonate.ninja/` today and this happened to me, after logging in it still just shows Login at the top right, no option to access Profile, etc (in Chrome). This does not happen for me when testing on `localhost:8080`, however.

**Comment by auggod** [comment] 2022-02-02 23:17
Login works but the legacy_id was no incremented anymore in the db. This is important for compat with older tables. I need to find out why.

**Comment by auggod** [comment] 2022-02-02 23:50
Looks like updating bun (db orm) above 1.x fixes the issue.

https://github.com/resonatecoop/user-api/pull/17

**Comment by auggod** [comment] 2022-02-04 16:10
I have update bun orm (both on id server and user-api)
I found out the key legacy_id on the users table for the dev server db didn't have the default value set to `nextval('users_legacy_id_seq'::regclass)`
It's weird because I'm sure it used to work before. We should do a db reset.

**Comment by auggod** [comment] 2022-02-04 16:11
@peterklingelhofer @jackhajb You can try again to create an account.

**Comment by peterklingelhofer** [comment] 2022-02-05 00:26
@auggod, just tried to make two accounts on there, one in Firefox and one in Chrome. It's been about ten minutes and I haven't received a confirmation email for either. 

When I try to do `Reset Password` from this stage (just to see if I could nudge things along) I'm seeing `ERROR: invalid input syntax for type timestamp with time zone: "null" (SQLSTATE 22007)` in the UI along with a 500 error response from the server: `POST https://id.resonate.ninja/password-reset 500`.

**Comment by auggod** [comment] 2022-02-05 14:06
The issue is that it cannot send emails in dev mode unless it's registered with mailgun. I can add yours to the email list. You can message me on telegram. I realize you cannot get in unless the email is verified.

**Comment by auggod** [comment] 2022-02-05 14:16
Looks like we reached the limit for authorized recipients in sandbox mode. I have manually confirmed your email address anyway.

**Comment by auggod** [comment] 2022-02-05 14:56
> When I try to do `Reset Password` from this stage (just to see if I could nudge things along) I'm seeing `ERROR: invalid input syntax for type timestamp with time zone: "null" (SQLSTATE 22007)` in the UI along with a 500 error response from the server: `POST https://id.resonate.ninja/password-reset 500`.

I have released a fix for this issue. Looks like a regression caused by bun (db orm) update to 1.x

**Comment by peterklingelhofer** [comment] 2022-02-05 16:28
@auggod, very nice. I'm logged in now! It appears this issue can now be closed.

A few things I ran into (perhaps I should create a new issue for these errors though or post them on the forum):
It says "Logging in as" and nothing follows, should it have the username there maybe?
<img width="408" alt="Screen Shot 2022-02-05 at 10 23 22 AM" src="https://user-images.githubusercontent.com/60944077/152649924-efa359d2-83bf-46a8-9141-d636c502a3e9.png">

Getting some errors when I navigate to a release:
<img width="1680" alt="Screen Shot 2022-02-05 at 10 24 38 AM" src="https://user-images.githubusercontent.com/60944077/152649928-793df773-f0ef-4b20-93be-1b61302278a7.png">

When I click in the top left Resonate icon to go back to home, or use the back button, I get these errors in the console as well:
<img width="1680" alt="Screen Shot 2022-02-05 at 10 24 51 AM" src="https://user-images.githubusercontent.com/60944077/152649938-d1de777a-5943-4040-9635-910d9055f172.png">

Happy to make a forum post for these issues if these are separate, but figured I'd post them here first in case it was a quick fix. Cheers, and thank you for all of your hard work on this. The new website is looking really fantastic!

**Comment by auggod** [comment] 2022-02-05 16:39
We should fallback to email until the user adds a display name

**Comment by auggod** [comment] 2022-02-05 16:39
The issue on the overtures release page can be ignored.

**Closed as completed** 2022-02-13 19:27 UTC
Labels: bug
